/*
-- Query: select * from attribute_master
LIMIT 0, 1000

-- Date: 2024-12-28 14:08
*/
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('N','PRODUCT_TYPE','NOTEBOOK',1,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('S','PRODUCT_TYPE','STATIONARY',2,2);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('P','PRODUCT_TYPE','PAPER',3,3);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('G','PRODUCT_TYPE','SPORTS',4,4);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('J','PRODUCT_SUB_TYPE','JUMBO',5,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('A4','PRODUCT_SUB_TYPE','A/4 BOOK',6,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('A5','PRODUCT_SUB_TYPE','A/5 BOOK',7,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('L','PRODUCT_SUB_TYPE','LONG BOOK',8,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('D','PRODUCT_SUB_TYPE','DRAWING BOOK',9,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('F','PRODUCT_SUB_TYPE','FULL SCAPE PAPER',10,3);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('P','PRODUCT_SUB_TYPE','PROJECT PAPER',11,3);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('P','PRODUCT_BRAND','PRIME ',12,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('R','PRODUCT_BRAND','REEGAL',13,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('72','PRODUCT_SPECS','100 PAGE',14,1);
INSERT INTO `` (`AM_ATRB_CODE`,`AM_ATRB_TYPE`,`AM_ATRB_VALUE`,`AM_ATRB_ID`,`AM_PARENT_ATRB_ID`) VALUES ('172','PRODUCT_SPECS','172 PAGES',15,1);
